### ISSUE TITLE
Setting State via SetState for one property

### ISSUE THREAD

**Issue by sbubaron** [DanWahlin/Observable-Store#212] opened 2022-03-02 05:27 UTC
First, thanks for a great library. It has been immensely useful and I appreciate your efforts and work in the angular community. 

I have a store which is based around a primary object (league) and some related properties like games, registrations, teams that belong to that league

When I add a game, I'd like force a refresh of the games array from my api (my api response contains a fully populated object that includes some calculated properties (winner/loser etc.) and other relationships which make me prefer relying on the server to be the source of truth rather than attempting to duplicate that logic locally. 

So I built a method on my store called refreshGames, which looks at the current league in the state, and calls my games http service to load all games for this league and then calls setState({games: games}); doing this drops the other properties from the state (league, registrations, teams).

is this intentional? what is the preferred way of keeping the unchanged items in the store/state? do I just pull them from the store first and then readd them in the setState call with the new games array?

I am using angular FWIW, your example seems to imply I should be able to setState on individual properties of the store, in your example you have customers and a specific customer, though the example doesn't get into this specific situation of having both objects populated.  

![observablestore-github](https://user-images.githubusercontent.com/10930702/156300893-08d35b7b-4dbb-450d-a0bb-d582ac9d3835.JPG)

*The games array being 0 length is intentional, in this case I "cleared" the schedule of all games. Whats not intentional is that the league/registrations/teams properties are missing. 

Thanks again.

**Comment by sbubaron** [comment] 2022-03-03 07:08
This is what I got going, but looking at your example, I definitely see some potential refactoring I should consider doing. 
It appears that in my code I'm subscribing to the http call inside the store, whereas you seem to prefer handling this in the component -- I guess in this way you are also able to properly display a loading screen in the component as well?

Your store 

`
@Injectable({
  providedIn: 'root'
})
export class SportingEventStoreService extends ObservableStore<SportingEventStoreState> {

  constructor(
    private leagueService: LeagueService,
    private playerRegistrationService: PlayerRegistrationService

  ) {
    super({ trackStateHistory: true, logStateChanges: true });

    const initialState = {

      league: null,
      registrations: [],
      teams: [],
    };


    this.setState(initialState, 'INIT_STATE');

  }

  setLeague(id: string) {

    if (!(this.getState().league?._id === id)) {


      const league$ = this.leagueService.getLeagueV4(id);
      const registrations$ = this.leagueService.getLeaguePlayerRegistrations(id);
      const teams$ = this.leagueService.getLeagueTeams(id);
      const games$ = this.leagueService.getLeagueGames(id);

      forkJoin([league$, registrations$, teams$, games$]).subscribe(res => {
        this.setState({
          league: res[0],
          registrations: res[1],
          teams: res[2],
          games: res[3]
        }, 'SPORTING EVENT SET');
      });
    }

  }

  reload() {

    if ((this.getState().league?._id)) {


      const league$ = this.leagueService.getLeagueV4(this.getState().league?._id);
      const registrations$ = this.leagueService.getLeaguePlayerRegistrations(this.getState().league?._id);
      const teams$ = this.leagueService.getLeagueTeams(this.getState().league?._id);
      const games$ = this.leagueService.getLeagueGames(this.getState().league?._id);

      forkJoin([league$, registrations$, teams$, games$]).subscribe(res => {
        this.setState({
          league: res[0],
          registrations: res[1],
          teams: res[2],
          games: res[3]
        }, 'SPORTING EVENT RELOADED');
      });
    }

  }


  reloadGames() {


    if (this.getState().league?._id) {

      let curLeague = this.getState().league;
      let curRegistrations = this.getState().registrations;
      let curTeams = this.getState().teams;

      this.leagueService.getLeagueGames(curLeague._id).subscribe(games => {

        this.setState({
          games: games,
        }, "REFRESH GAMES");

      });

    }
  }


  refreshState(leagueId: string) {
    const league$ = this.leagueService.getLeagueV4(leagueId);
    const registrations$ = this.leagueService.getLeaguePlayerRegistrations(leagueId);
    const teams$ = this.leagueService.getLeagueTeams(leagueId);
    const games$ = this.leagueService.getLeagueGames(leagueId);
    return forkJoin([league$, registrations$, teams$, games$]).pipe(
      tap(res => {
        this.setState({
          league: res[0],
          registrations: res[1],
          teams: res[2],
          games: res[3]
        });
      }));

  }

  // refreshPlayerRegistrations(leagueId: string) {

  //   const registrations$ = this.leagueService.getLeaguePlayerRegistrations(leagueId);
  //   const teams$ = this.leagueService.getLeagueTeams(leagueId);

  //   return forkJoin([registrations$, teams$]).pipe(
  //     tap(res => {
  //       this.setState({
  //         registrations: res[0],
  //         teams: res[1],

  //         league: this.getState().league,
  //         games: this.getState().games

  //       });
  //     }));

  // }



  updateLeague(league: League) {
    return this.leagueService.updateLeague(league).pipe(
      switchMap((l) => {
        // this.setState({ league }, 'UPDATE LEAGUE');
        return this.refreshState(league._id);
      }),
      catchError(this.handleError)
    );
  }

  addRegistration(playerRegistration: PlayerRegistration) {
    return this.playerRegistrationService.addPlayerRegistration(playerRegistration).pipe(
      switchMap((l) => {
        // this.setState({ league }, 'UPDATE LEAGUE');
        return this.refreshState(this.getState().league?._id);
      }),
      catchError(this.handleError)
    );
  }

  updateRegistration(playerRegistration: PlayerRegistration) {
    return this.playerRegistrationService.updatePlayerRegistration(playerRegistration).pipe(
      switchMap((l) => {
        // this.setState({ league }, 'UPDATE LEAGUE');
        return this.refreshState(this.getState().league?._id);
      }),
      catchError(this.handleError)
    );
  }

  deleteRegistrations() {
    return this.playerRegistrationService.deleteLeagueRegistrations(this.getState().league?._id).pipe(
      switchMap((l) => {
        // this.setState({ league }, 'UPDATE LEAGUE');
        return this.refreshState(this.getState().league?._id);
      }),
      catchError(this.handleError)
    );
  }

  private handleError(error: any) {
    console.error('server error:', error);
    if (error.error instanceof Error) {
      const errMessage = error.error.message;
      return throwError(() => errMessage);
    }
    return throwError(() => error || 'Server error');
  }

 


}`

**Comment by DanWahlin** [comment] 2022-03-03 17:53
You're fine subscribing in the service. That part wouldn't matter. The sample I mentioned is just a simple demo of multiple properties added to the store and being updated.

You might try stepping through the setState() call (where you see the problem happen) into the observable store base that I showed above to see what's coming in to be set, what's currently in the store, etc. That might lead to more information about what might be causing that.

Without a project for me to run that reproduces what you're seeing, it's hard to say could be leading to that behavior. Due to the amount of async calls going on, I'm wondering if it's a timing issue potentially. Hard to say for sure. Hopefully the debug suggestion above may give you some more info to go on.

**Comment by DanWahlin** [comment] 2022-04-28 19:21
I'm going to close this out since it's old now, but feel free to re-open it if you haven't figured out a solution.

**Closed by DanWahlin** 2022-04-28 19:21 UTC
